package jdbcspark

import java.sql.Timestamp
import java.time.Instant

object Faker {
  // Create a random user
  def randomUser(userId: Option[Int] = None): User = {
    val instant = Instant.now()
    val timestamp = Timestamp.from(instant)
    // get a random id between 0 and 100000000 if no id is provided
    val id = userId.getOrElse(scala.util.Random.nextInt(100000000))
    // get a random first name from from the list
    val firstName = scala.util.Random.shuffle(firstNames).head
		// get a random last name from from the list
    val lastName = scala.util.Random.shuffle(lastNames).head
		// get a numFriends between 0 and 1000
    val numFriends = scala.util.Random.nextInt(1000)
		// get a age between 0 and 100
    val age = scala.util.Random.nextInt(100)
    User(id, firstName, lastName, age, numFriends, timestamp)
  }

  val firstNames = List(
    "Alex",
    "Ben",
    "Charlie",
    "Dave",
    "Emily",
    "Frank",
    "George",
    "Hannah",
    "Isaac",
    "Jake",
    "Kate",
    "Lucy",
    "Michael",
    "Nina",
    "Olivia",
    "Peter",
    "Quinn",
    "Rachel",
    "Sam",
    "Tess",
    "Tom",
    "Victoria",
    "William",
    "Sarah",
    "John",
    "Mary",
    "Peter",
    "Bill",
    "Raphaël",
    "Jean",
    "Paul",
    "Jacques",
    "Marie",
    "Anne",
    "Julie",
    "Julien",
    "Juliette"
  )
  val lastNames = List(
    "Smith",
    "Johnson",
    "Williams",
    "Jones",
    "Brown",
    "Davis",
    "Miller",
    "Wilson",
    "Moore",
    "Taylor",
    "Anderson",
    "Thomas",
    "Jackson",
    "White",
    "Harris",
    "Martin",
    "Thompson",
    "Garcia",
    "Martinez",
    "Robinson",
    "Clark",
    "Rodriguez",
    "Lewis",
    "Lee",
    "Walker",
    "Hall",
    "Allen",
    "Young",
    "Hernandez",
    "King",
    "Wright",
    "Lopez",
    "Hill",
    "Scott",
    "Green",
    "Adams",
    "Baker",
    "Gonzalez",
    "Nelson",
    "Carter",
    "Mitchell",
    "Perez",
    "Roberts",
    "Turner",
    "Phillips",
    "Campbell",
    "Parker",
    "Evans",
    "Edwards",
    "Collins",
    "Stewart",
    "Sanchez",
    "Morris",
    "Rogers",
    "Reed",
    "Cook",
    "Morgan",
    "Bell",
    "Murphy",
    "Bailey",
    "Rivera",
    "Cooper",
    "Richardson",
    "Cox",
    "Howard",
    "Ward",
    "Torres",
    "Peterson",
    "Gray",
    "Ramirez",
    "James",
    "Watson",
    "Brooks",
    "Kelly",
    "Sanders",
    "Price",
    "Bennett",
    "Wood",
    "Barnes",
    "Ross",
    "Henderson",
    "Coleman",
    "Jenkins",
    "Perry",
    "Powell",
    "Long",
    "Patterson",
    "Hughes",
    "Flores",
    "Washington",
    "Butler",
    "Simmons",
    "Foster",
    "Gonzales",
    "Bryant",
    "Alexander",
    "Russell",
    "Griffin",
    "Diaz",
    "Hayes",
    "Martin",
    "Bernard",
    "Thomas",
    "Robert",
    "Richard"
  )

}
